// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *Order) setDefaults() {
	{
		val := string("")
		s.OrderUUID.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OrderDetail) setDefaults() {
	{
		val := bool(false)
		s.CrmRefunded.SetTo(val)
	}
	{
		val := bool(false)
		s.CrmBlacklisted.SetTo(val)
	}
	{
		val := bool(false)
		s.CrmStoppedRecurring.SetTo(val)
	}
	{
		val := bool(false)
		s.Resolved.SetTo(val)
	}
	{
		val := bool(false)
		s.OrderConfirmed.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OrderTransaction) setDefaults() {
	{
		val := bool(false)
		s.PanLocked.SetTo(val)
	}
	{
		val := bool(false)
		s.PreserveGateway.SetTo(val)
	}
	{
		val := bool(false)
		s.IsRecurring.SetTo(val)
	}
	{
		val := bool(false)
		s.IsChargeback.SetTo(val)
	}
	{
		val := bool(false)
		s.IsFraud.SetTo(val)
	}
	{
		val := bool(false)
		s.IsRma.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *Payment) setDefaults() {
	{
		val := PaymentCCType("visa")
		s.CCType.SetTo(val)
	}
	{
		val := bool(false)
		s.PrepaidMatch.SetTo(val)
	}
}
