// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ProcessUpload implements processUpload operation.
//
// The default and main end point used for sending order data records to be added into the database.
//
// POST /
func (UnimplementedHandler) ProcessUpload(ctx context.Context, req *Order) (r *GoResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GoResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GoResponseStatusCode) {
	r = new(GoResponseStatusCode)
	return r
}
