/*
 * Order Uploader
 *
 * Takes cleaned and validated order data records as input and enters the record into the database tables
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DefaultAPIService is a service that implements the logic for the DefaultAPIServicer
// This service should implement the business logic for every endpoint for the DefaultAPI API.
// Include any external packages or services that will be required by this service.
type DefaultAPIService struct {
}

// NewDefaultAPIService creates a default api service
func NewDefaultAPIService() DefaultAPIServicer {
	return &DefaultAPIService{}
}

// ProcessUpload - Main end point for processing records
func (s *DefaultAPIService) ProcessUpload(ctx context.Context, order Order) (ImplResponse, error) {
	// TODO - update ProcessUpload with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, GoResponse{}) or use other options such as http.Ok ...
	// return Response(200, GoResponse{}), nil

	// TODO: Uncomment the next line to return response Response(0, GoResponse{}) or use other options such as http.Ok ...
	// return Response(0, GoResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ProcessUpload method not implemented")
}
