/*
 * Order Uploader
 *
 * Takes cleaned and validated order data records as input and enters the record into the database tables
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type OrderBilling struct {

	Mid string `json:"Mid,omitempty"`

	OrderTotal float64 `json:"Order_total,omitempty"`

	Currency string `json:"Currency,omitempty"`

	UsdAmount float64 `json:"Usd_amount,omitempty"`

	SalesTax float64 `json:"Sales_tax,omitempty"`

	SalesTaxAmount float64 `json:"Sales_tax_amount,omitempty"`

	TotalAmountRefunded float64 `json:"Total_amount_refunded,omitempty"`

	BillingCycle int32 `json:"Billing_cycle,omitempty"`

	RecurringDate string `json:"Recurring_date,omitempty"`

	RetryDate string `json:"Retry_date,omitempty"`

	BillingAddressId Address `json:"Billing_address_id,omitempty"`
}

// AssertOrderBillingRequired checks if the required fields are not zero-ed
func AssertOrderBillingRequired(obj OrderBilling) error {
	if err := AssertAddressRequired(obj.BillingAddressId); err != nil {
		return err
	}
	return nil
}

// AssertOrderBillingConstraints checks if the values respects the defined constraints
func AssertOrderBillingConstraints(obj OrderBilling) error {
	return nil
}
