/*
 * Order Uploader
 *
 * Takes cleaned and validated order data records as input and enters the record into the database tables
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type Contact struct {

	ContactPhone string `json:"Contact_phone"`

	ContactEmail string `json:"Contact_email"`

	ContactAddressId Address `json:"Contact_address_id,omitempty"`
}

// AssertContactRequired checks if the required fields are not zero-ed
func AssertContactRequired(obj Contact) error {
	elements := map[string]interface{}{
		"Contact_phone": obj.ContactPhone,
		"Contact_email": obj.ContactEmail,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertAddressRequired(obj.ContactAddressId); err != nil {
		return err
	}
	return nil
}

// AssertContactConstraints checks if the values respects the defined constraints
func AssertContactConstraints(obj Contact) error {
	return nil
}
