/*
 * Order Uploader
 *
 * Takes cleaned and validated order data records as input and enters the record into the database tables
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type OrderShipping struct {

	ShippingMethodName string `json:"Shipping_method_name,omitempty"`

	ShippingDate string `json:"Shipping_date,omitempty"`

	TrackingNumber string `json:"Tracking_number,omitempty"`

	ShippingAddressId Address `json:"Shipping_address_id,omitempty"`
}

// AssertOrderShippingRequired checks if the required fields are not zero-ed
func AssertOrderShippingRequired(obj OrderShipping) error {
	if err := AssertAddressRequired(obj.ShippingAddressId); err != nil {
		return err
	}
	return nil
}

// AssertOrderShippingConstraints checks if the values respects the defined constraints
func AssertOrderShippingConstraints(obj OrderShipping) error {
	return nil
}
