/*
 * Order Uploader
 *
 * Takes cleaned and validated order data records as input and enters the record into the database tables
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



type Address struct {

	FirstName string `json:"First_name,omitempty"`

	LastName string `json:"Last_name,omitempty"`

	StreetAddr string `json:"Street_addr"`

	StreetAddr2 string `json:"Street_addr_2,omitempty"`

	City string `json:"City,omitempty"`

	State string `json:"State"`

	Postcode string `json:"Postcode"`

	Country string `json:"Country"`

	AddressCreated time.Time `json:"Address_created,omitempty"`
}

// AssertAddressRequired checks if the required fields are not zero-ed
func AssertAddressRequired(obj Address) error {
	elements := map[string]interface{}{
		"Street_addr": obj.StreetAddr,
		"State": obj.State,
		"Postcode": obj.Postcode,
		"Country": obj.Country,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertAddressConstraints checks if the values respects the defined constraints
func AssertAddressConstraints(obj Address) error {
	return nil
}
