/*
 * Order Uploader
 *
 * Takes cleaned and validated order data records as input and enters the record into the database tables
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type GoResponse struct {

	// Short explanation of either the successful or failed processing of order record
	Message string `json:"message,omitempty"`

	// Indicator on the outcome of the submitted order record
	Outcome string `json:"outcome,omitempty"`

	// List of failures for non-required data blocks
	NonFatal []GoResponseNonFatalInner `json:"non-fatal,omitempty"`
}

// AssertGoResponseRequired checks if the required fields are not zero-ed
func AssertGoResponseRequired(obj GoResponse) error {
	for _, el := range obj.NonFatal {
		if err := AssertGoResponseNonFatalInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertGoResponseConstraints checks if the values respects the defined constraints
func AssertGoResponseConstraints(obj GoResponse) error {
	return nil
}
