/*
 * Order Uploader
 *
 * Takes cleaned and validated order data records as input and enters the record into the database tables
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



type OrderProductInner struct {

	ProductId int32 `json:"Product_id,omitempty"`

	ProductQuantity int32 `json:"Product_quantity,omitempty"`

	UpsellProductId int32 `json:"Upsell_product_id,omitempty"`

	UpsellProductQuantity int32 `json:"Upsell_product_quantity,omitempty"`

	OrderProductCreated time.Time `json:"Order_product_created,omitempty"`
}

// AssertOrderProductInnerRequired checks if the required fields are not zero-ed
func AssertOrderProductInnerRequired(obj OrderProductInner) error {
	return nil
}

// AssertOrderProductInnerConstraints checks if the values respects the defined constraints
func AssertOrderProductInnerConstraints(obj OrderProductInner) error {
	return nil
}
