/*
 * Order Uploader
 *
 * Takes cleaned and validated order data records as input and enters the record into the database tables
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



type OrderNoteInner struct {

	NoteMessage string `json:"Note_message,omitempty"`

	NoteCreated time.Time `json:"Note_created,omitempty"`
}

// AssertOrderNoteInnerRequired checks if the required fields are not zero-ed
func AssertOrderNoteInnerRequired(obj OrderNoteInner) error {
	return nil
}

// AssertOrderNoteInnerConstraints checks if the values respects the defined constraints
func AssertOrderNoteInnerConstraints(obj OrderNoteInner) error {
	return nil
}
