version: '3.9'
services:
  demo:
    container_name: demo
    build:
      context: ./
      dockerfile: Dockerfile
    platform: linux/arm64
    ports:
      - "8080:8080"

  swaggerui:
    image: swaggerapi/swagger-ui
    container_name: swaggerui
    ports:
      - "80:8080"
    environment:
      SWAGGER_JSON: "/swagger.yaml"
      DEFAULT_MODELS_EXPAND_DEPTH: "5"
      TRY_IT_OUT_ENABLED: "true"

    volumes:
      - "./swagger.yaml:/swagger.yaml"

